# General parser for phylip formatted distance matrices, e.g. generated by the
# EMBOSS tool "distmat"
# Returns a tidy tibble, where sequence_1 is always before sequence_2 in sorting
# order. 
# Important: the "skip" parameter might need to be adjusted. This is the number
# of lines before the actual distance values start.
read_phylip_distmat <- function(fin, include_diagonal = T, skip = 8) {

  distances_raw <- read_tsv(fin, col_names = F, skip = skip) %>%
    separate(ncol(.), into = c("name", "number"), sep = " ")
  
  names <- distances_raw$name
  
  n <- length(names)
  
  distances <- distances_raw %>%
    select(2:(n + 1)) %>%
    `names<-`(names) %>%
    mutate(sequence_1 = !! names) %>%
    gather(key = "sequence_2", value = "distance", - sequence_1, na.rm = T) %>%
    mutate_at("distance", as.double)
  
  distances_1 <- distances %>%
    filter(sequence_1 > sequence_2)
  
  distances_2 <- distances %>%
    filter(sequence_2 > sequence_1) %>%
    mutate(sequence_1_temp = sequence_2, sequence_2_temp = sequence_1) %>%
    select(sequence_1 = sequence_1_temp, sequence_2 = sequence_2_temp)
  
  distances <- bind_rows(distances_1, distances_2)
  
  if (! include_diagonal) {
    distances <- distances %>%
      filter(sequence_1 != sequence_2)
  }
  
  distances
  
}

# Parser for orthogroup data from orthofinder. 
# Returns tidy table where each row represents a gene. 
read_orthogroups <- function(orthofinder_dir) {
  
  genes_assigned <- orthofinder_dir %>%
    paste0("/Orthogroups.csv") %>%
    readr::read_tsv(col_names = T) %>%
    rename(orthogroup = X1) %>%
    gather(key = "genome", value = "gene", na.rm = T, - orthogroup) %>%
    separate_rows(gene, sep = ", ")
  
  genes_unassigned <- orthofinder_dir %>%
    paste0("/Orthogroups_UnassignedGenes.csv") %>%
    readr::read_tsv(col_names = T) %>%
    rename(orthogroup = X1) %>%
    gather(key = "genome", value = "gene", na.rm = T, - orthogroup)
  
  genes <- bind_rows(genes_assigned, genes_unassigned)
  
  genes
  
}

# Parser for hmmer domtables. 
# Returns tidy table where each row is a hit. 
read_hmmer_domtbl <- function(fin) {
  
  read_table2(fin, comment = "#", col_names = F) %>%
    `names<-`(c(
      "target", "target_accession", "target_length", 
      "query", "query_accession", "query_length", 
      "e_value_full", "score_full", "bias_full",
      "i", "i_max", "c_e_value", "i_e_value", "score", "bias", 
      "hmm_from", "hmm_to", "ali_from", "ali_to", "env_from", "env_to",
      "acc", "target_description"
    ))
  
}